name: Setup
description: Setup environment

runs:
  using: composite
  steps:
    - name: Setup mamba
      uses: mamba-org/setup-micromamba@v2
      with:
        environment-file: environment/environment-linux.yaml
        cache-downloads: false
        cache-environment: true
        init-shell: bash
        post-cleanup: 'all'