name: VyPER
channels:
  - conda-forge
dependencies:
  - python=3.13.*
  - pip
  - pip:
    - torch==2.11.0
    - torch_geometric
    - https://data.pyg.org/whl/torch-2.9.0%2Bcpu/torch_scatter-2.1.2-cp313-cp313-macosx_10_13_universal2.whl
    - numpy
    - pandas
    - lightning
    - tensorboard
    - jupyterlab
    - matplotlib
    - h5py
    - torch-hep==0.0.5
    - hydra-core
    - rich
    - optuna
    - optuna-dashboard
    - onnx
    - onnxscript
    - onnxruntime