name: VyPER
channels:
  - conda-forge
dependencies:
  - python=3.13.*
  - pip
  - pip:
    - https://download-r2.pytorch.org/whl/cpu/torch-2.14.0-cp313-cp313-macosx_14_0_arm64.whl
    - torch_geometric
    - numpy
    - pandas
    - lightning
    - tensorboard
    - jupyterlab
    - matplotlib
    - h5py
    - torch-hep==0.0.5
    - hydra-core
    - rich
    - optuna
    - optuna-dashboard