# NVIDIA Grace Hopper and Grace Blackwell Superchip
name: VyPER
channels:
  - nvidia
dependencies:
  - python=3.13.*
  - pip
  - cuda-toolkit=13.0
  - pip:
    - https://download.pytorch.org/whl/cu130/torch-2.11.0%2Bcu130-cp313-cp313-manylinux_2_28_aarch64.whl
    - torch_geometric
    # torch_scatter is currently unavailable for CUDA 13.0 ARM64
    - numpy
    - pandas
    - lightning
    - tensorboard
    - jupyterlab
    - matplotlib
    - h5py
    - torch-hep==0.0.5
    - hydra-core
    - rich
    - optuna
    - optuna-dashboard
    - onnx
    - onnxscript
    - onnxruntime
    - onnxslim
