name: VyPER
channels:
  - nvidia
dependencies:
  - python=3.13.*
  - pip
  - cuda-toolkit=13.0
  - pip:
    - https://download-r2.pytorch.org/whl/cu130/torch-2.14.0%2Bcu130-cp313-cp313-manylinux_2_28_x86_64.whl
    - torch_geometric
    - numpy
    - pandas
    - lightning
    - tensorboard
    - jupyterlab
    - matplotlib
    - h5py
    - torch-hep==0.0.5
    - hydra-core
    - rich
    - optuna
    - optuna-dashboard