name: VyPER
channels:
  - nvidia
dependencies:
  - python=3.13.*
  - pip
  - cuda-toolkit=13.0
  - pip:
    - torch==2.9.1
    - torch_geometric
    - https://data.pyg.org/whl/torch-2.9.0%2Bcu130/torch_scatter-2.1.2%2Bpt29cu130-cp313-cp313-linux_x86_64.whl
    - numpy
    - pandas
    - lightning
    - tensorboard
    - jupyterlab
    - matplotlib
    - h5py
    - torch-hep==0.0.5
    - hydra-core
    - rich
    - optuna
    - optuna-dashboard