datasets:
  train_set:        null
  val_set:          null
  predict_set:      null
  event_filter:     null
  train_val_split:  0.9
  drop_last:        true

network:
  message_feats:      64
  num_attn_heads:     8
  num_message_layers: 3
  hyperedge_feats:    128
  hyperedge_order:    3
  num_sampling_steps: 200

training:
  learning_rate:      0.0003
  weight_decay:       0.01
  optimizer:          AdamW
  loss_reduction:     mean
  alpha:              0.8
  eta:                0.8
  dropout:            0.01
  gradient_clip:      1.
  epochs:             500
  batch_size:         4096
  grad_accum_batches: 1
  patience:           10
  save_directory:     logs
  continue_from_ckpt: null

predicting:
  model_directory:    logs/version_0
  model_choice:       min-loss
  batch_size:         4096
  edge_reduction:     mean
  save_as:            ./output.h5

device:
  accelerator:        gpu
  num_devices:        1
  num_workers:        12

input:
  nodes:
    JET: 0
    ELECTRON: 1
    MUON: 2

  node_features:
    - e
    - eta
    - phi
    - pt
    - btag
    - charge

  node_4vector_definition:
    functional: MomentumTensor.EEtaPhiPt
    ordered_inputs:
      - e
      - eta
      - phi
      - pt

  node_transforms:
    - torch.log(x)
    - x / math.pi
    - x / math.pi
    - torch.log(x)
    - x
    - x

  edge_features:
    - (e1.eta - e2.eta)
    - torch.arctan2(torch.sin(e1.phi-e2.phi),torch.cos(e1.phi-e2.phi))
    - torch.sqrt((e1.eta - e2.eta)*(e1.eta - e2.eta) + torch.arctan2(torch.sin(e1.phi-e2.phi),torch.cos(e1.phi-e2.phi))*torch.arctan2(torch.sin(e1.phi-e2.phi),torch.cos(e1.phi-e2.phi)))
    - (e1 + e2).m

  edge_transforms:
    - x
    - x
    - x
    - torch.log(torch.clamp(x, min=1e-9)) # torch.log(x)

  global_features:
    - njet
    - nbTagged
    - nelectron
    - nmuon
    - met_met
    - met_phi

  global_transforms:
    - x / 2
    - x / 2
    - x / 2
    - x / 2
    - torch.log(x)
    - x

target:
  edge:
    bl:
      - ['0-1','1-1'] # b el+
      - ['0-1','2-1'] # b mu+
      - ['0-4','1-2'] # bbar el-
      - ['0-4','2-2'] # bbar el-

  neutrinos:
    node_label: 3
    associated_nodes:
      - 1
      - 2
    features:
      - px
      - py
      - pz
    transforms:
      - (x + 0.0032) / 50.1241
      - (x + 0.0145) / 50.1411
      - (x + 0.0276) / 156.3070
    reverse_transforms:
      - x * 50.1241 - 0.0032
      - x * 50.1411 - 0.0145
      - x * 156.3070 - 0.0276
    4vector_definition:
      functional: MomentumTensor
      ordered_inputs:
        - torch.sqrt((px*px)+(py*py)+(pz*pz))
        - px
        - py
        - pz
  
  hyperedge:
    top:
      - ['0-1','1-2','3-1-2']
      - ['0-1','2-2','3-2-2']
      - ['0-2','1-1','3-1-1']
      - ['0-2','2-1','3-2-1']
