# -------------------------------------- #
#             Common Settings            #
# -------------------------------------- #
datasets:
  train_set:        null
  val_set:          null
  predict_set:      null
  tune_set:         null
  event_filter:     null
  force_reload:     false
  train_val_split:  0.9
  drop_last:        true

network:
  message_feats:      64
  attn_feats:         128
  num_attn_heads:     8
  num_message_layers: 3
  num_dit_blocks:     4
  hyperedge_feats:    128
  hyperedge_order:    3

training:
  learning_rate:      0.0003
  weight_decay:       0.01
  momentum:           0.0
  optimizer:          AdamW
  loss_reduction:     mean
  alpha:              0.8
  eta:                0.8
  dropout:            0.01
  gradient_clip:      1.
  epochs:             500
  batch_size:         4096
  num_sampling_steps: 50
  grad_accum_batches: 1
  patience:           10
  save_directory:     logs
  continue_from_ckpt: null
  lr_scheduler:
    method: torch.optim.lr_scheduler.ReduceLROnPlateau
    kwargs:
      mode:   min
      factor: 0.8
      patience: 5
  save_ckpts:
    accuracy/edge_channel_1: max
    accuracy/dR_mean: min

predicting:
  model_directory:    ${training.save_directory}/version_0
  model_choice:       min-loss
  batch_size:         4096
  num_sampling_steps: 200
  edge_reduction:     mean
  save_as:            ${predicting.model_directory}/output.h5

device:
  accelerator:        gpu
  num_devices:        1
  num_workers:        12

onnx_export:
  model_directory:    ${predicting.model_directory}
  model_choice:       ${predicting.model_choice}
  save_as:            ${predicting.model_directory}/VyPER.onnx
  opset_version:      21
  consistence_check:
    run_check:  True
    rtol:       1e-04
    atol:       1e-04

# -------------------------------------- #
#     Hyperparameter Tuning Settings     #
# -------------------------------------- #
tune:
  n_trials:   100
  epochs:     5
  study_name: VyPER-Tuning
  save_dir:   ./tuning
  sqlite:     sqlite:///tuning.db
  monitors:
    - accuracy/dR_mean
    - loss/validation_loss
  directions:
    - minimize
    - minimize

  hyperparameters:
    network:
      message_feats:
        - int
        - 32
        - 128
        - 16
      num_attn_heads:
        - int
        - 4
        - 32
        - 4
      num_message_layers:
        - int
        - 3
        - 6

    training:
      learning_rate:
        - loguniform
        - 0.0001
        - 0.001
      weight_decay:
        - loguniform
        - 0.001
        - 0.01
      alpha:
        - float
        - 0.1
        - 0.9
      eta:
        - float
        - 0.1
        - 0.9
      dropout:
        - loguniform
        - 0.0001
        - 0.01


# -------------------------------------- #
#        Dataset-dependent Settings      #
# -------------------------------------- #
input:
  nodes:
    JET: 0
    ELECTRON: 1
    MUON: 2

  node_features:
    - e
    - eta
    - phi
    - pt
    - btag
    - charge

  node_4vector_definition:
    functional: MomentumTensor.EEtaPhiPt
    ordered_inputs:
      - e
      - eta
      - phi
      - pt

  node_transforms:
    - torch.log(x)
    - x / math.pi
    - x / math.pi
    - torch.log(x)
    - x
    - x

  edge_features:
    - (e1.eta - e2.eta)
    - torch.arctan2(torch.sin(e1.phi-e2.phi),torch.cos(e1.phi-e2.phi))
    - torch.sqrt((e1.eta - e2.eta)*(e1.eta - e2.eta) + torch.arctan2(torch.sin(e1.phi-e2.phi),torch.cos(e1.phi-e2.phi))*torch.arctan2(torch.sin(e1.phi-e2.phi),torch.cos(e1.phi-e2.phi)))
    - (e1 + e2).m

  edge_transforms:
    - x
    - x
    - x
    - torch.log(torch.clamp(x, min=1e-9)) # torch.log(x)

  global_features:
    - njet
    - nbTagged
    - nelectron
    - nmuon
    - met_met
    - met_phi

  global_transforms:
    - x / 2
    - x / 2
    - x / 2
    - x / 2
    - torch.log(x)
    - x

target:
  topology:
    edge: 4
    hyperedge: 0
    neutrinos: 2

  edge:
    bl:
      - ['0-1','1-1'] # b el+
      - ['0-1','2-1'] # b mu+
      - ['0-4','1-2'] # bbar el-
      - ['0-4','2-2'] # bbar el-

  neutrinos:
    node_label: 3
    associated_nodes:
      - 1
      - 2
    features:
      - px
      - py
      - pz
    transforms:
      - (x + 0.0032) / 50.1241
      - (x + 0.0145) / 50.1411
      - (x + 0.0276) / 156.3070
    reverse_transforms:
      - x * 50.1241 - 0.0032
      - x * 50.1411 - 0.0145
      - x * 156.3070 - 0.0276
    4vector_definition:
      functional: MomentumTensor
      ordered_inputs:
        - torch.sqrt((px*px)+(py*py)+(pz*pz))
        - px
        - py
        - pz
