name: Setup

on:
  workflow_call:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Conda for Python 3.13
        uses: conda-incubator/setup-miniconda@v4
        with:
          python-version: 3.13
          auto-update-conda: true

      - name: Add conda to system path
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          echo $CONDA/bin >> $GITHUB_PATH

      - name: Install dependencies
        continue-on-error: true
        run: |
          conda env update --file environment/environment-linux.yaml --name base
          pip install pytest    
