name: Testing

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "0 6 * * *"

jobs:
  test:
    steps:
      - name: Run tests
      - uses: ./.github/actions/setup
      - run: |
          pytest test/ -v