name: Testing

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "0 6 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup

      - name: Run tests
        run: |
          pytest test/ -v